- name: Register GitLab runner
  hosts: "{{ target_node }}"
  gather_facts: no
  tasks:
    - name: Register runner
      shell: |
        /home/gitlab-runner-user/gitlab-runner/out/binaries/gitlab-runner-linux-riscv64 register --non-interactive \
          --name "{{runner_name}}" \
          --url "{{ gitlab_url }}" \
          --token "{{ registration_token }}" \
          --executor docker \
          --docker-image riscv64/debian:trixie-slim
      register: result
      changed_when: false
      ignore_errors: yes

    - name: Debug runner registration output
      debug:
        var: result

    - name: Fail if runner verification failed
      fail:
        msg: "Invalid Gitlab Registration Token (verification failed)"
      when:
        - result is defined
        - "'ERROR: Verifying runner... failed' in result.stderr or 'is not valid' in result.stderr or 'Failed to verify the runner.' in result.stderr"

    - name: Fail if request cannot be processed
      fail:
        msg: "Invalid Gitlab Registration Token or GitLab server URL (unprocessable entity)"
      when:
        - result is defined
        - "'status=422 Unprocessable Entity' in result.stderr"

    - name: Fail if runner registration was not successful
      fail:
        msg: "Runner registration failed for an unknown reason. Output: {{ result.stdout + result.stderr }}"
      when:
        - result is defined
        - "'Runner registered successfully.' not in (result.stdout + result.stderr)"

    - name: Catch-all failure if command failed and none of the above matched
      fail:
        msg: "Runner registration failed with unknown error. Full output: {{ result.stdout + result.stderr }}"
      when:
        - result is defined
        - result.rc != 0
        - "'ERROR: Verifying runner... failed' not in result.stderr"
        - "'ERROR: Verifying runner... is not valid' not in result.stderr"
        - "'status=422 Unprocessable Entity' not in result.stderr"
        - "'Runner registered successfully.' not in (result.stdout + result.stderr)"
